env:
    # OrangeFox Sync Repository
    TWRP_SYNC: https://github.com/TeamWin/android_bootable_recovery
    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: -1001526603733
    TG_TOKEN: 5775634073:AAEU7xWzDSvuWnKQU_GHJHIN6WGAf6RwR4k

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - curl -sL https://raw.githubusercontent.com/harshjaat98/OrangeFox-CI-1/twrp/scripts/checks.sh | bash

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/harshjaat98/OrangeFox-CI-1/twrp/scripts/sync.sh | bash

  Build_script:
      - curl -sL https://raw.githubusercontent.com/harshjaat98/OrangeFox-CI-1/twrp/scripts/build.sh | bash

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - curl https://raw.githubusercontent.com/harshjaat98/OrangeFox-CI-1/twrp/scripts/upload.sh | bash
